services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=picpaydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
